// <auto-generated />
using System;
using Eligibility.Api.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Eligibility.Api.Infrastructure.Data.Migrations
{
    [DbContext(typeof(EligibilityDbContext))]
    partial class EligibilityDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Eligibility.Api.Domain.Models.EligibilityResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DebtToIncomeRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DecisionSummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeclaredMonthlyIncome")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ExistingEmiObligations")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RequestedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RuleVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationId");

                    b.ToTable("EligibilityResults", (string)null);
                });

            modelBuilder.Entity("Eligibility.Api.Domain.Models.RuleResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActualValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EligibilityResultId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExpectedValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("Passed")
                        .HasColumnType("bit");

                    b.Property<string>("RuleCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("EligibilityResultId");

                    b.ToTable("RuleResults", (string)null);
                });

            modelBuilder.Entity("Eligibility.Api.Domain.Models.RuleResult", b =>
                {
                    b.HasOne("Eligibility.Api.Domain.Models.EligibilityResult", null)
                        .WithMany("RuleResults")
                        .HasForeignKey("EligibilityResultId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Eligibility.Api.Domain.Models.EligibilityResult", b =>
                {
                    b.Navigation("RuleResults");
                });
#pragma warning restore 612, 618
        }
    }
}
